Start fitting
alpha = 1e-4
{'hidden_layer_sizes': (60, 40)}
MLP_Test

**92.502%** (2788/3014)
MLP_TrainingTest
**91.350%** (26740/29272)


--------------------------------------------------------------------------------
LokyProcess-5 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/svclaw2000/.local/lib/python3.5/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 204, in <module>
    exitcode = process_obj._bootstrap()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 269, in _bootstrap
    sys.stderr.flush()
OSError: [Errno 5] Input/output error


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-8 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/svclaw2000/.local/lib/python3.5/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 204, in <module>
    exitcode = process_obj._bootstrap()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 269, in _bootstrap
    sys.stderr.flush()
OSError: [Errno 5] Input/output error


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-4 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/svclaw2000/.local/lib/python3.5/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 204, in <module>
    exitcode = process_obj._bootstrap()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 269, in _bootstrap
    sys.stderr.flush()
OSError: [Errno 5] Input/output error


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-1 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/svclaw2000/.local/lib/python3.5/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 204, in <module>
    exitcode = process_obj._bootstrap()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 269, in _bootstrap
    sys.stderr.flush()
OSError: [Errno 5] Input/output error


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-3 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/svclaw2000/.local/lib/python3.5/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 204, in <module>
    exitcode = process_obj._bootstrap()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 269, in _bootstrap
    sys.stderr.flush()
OSError: [Errno 5] Input/output error


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-6 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/svclaw2000/.local/lib/python3.5/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 204, in <module>
    exitcode = process_obj._bootstrap()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 269, in _bootstrap
    sys.stderr.flush()
OSError: [Errno 5] Input/output error


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-7 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/svclaw2000/.local/lib/python3.5/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 204, in <module>
    exitcode = process_obj._bootstrap()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 269, in _bootstrap
    sys.stderr.flush()
OSError: [Errno 5] Input/output error


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-2 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/svclaw2000/.local/lib/python3.5/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 204, in <module>
    exitcode = process_obj._bootstrap()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 269, in _bootstrap
    sys.stderr.flush()
OSError: [Errno 5] Input/output error


--------------------------------------------------------------------------------
